[workspace]
members = [ "aftgraphs-macros","imgui-wgpu","triangle" ]
exclude = [ "imgui-rs" ]

[package]
name = "aftgraphs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
futures-intrusive = "0.5"
wgpu = { version="0.18", features=["webgl", "spirv"] }
winit = { version="0.29.3", features=["rwh_05", "wayland", "x11"] }
current_platform = "0.2"
async-mutex = "1.4"
log = "0.4"
serde = { version="1.0", features=["derive"] }
toml = "0.8"
copypasta = "0.10"
bytemuck = { version = "1.14", features = ["derive"] }
smallvec = "1.13"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
clap = "4.4"
env_logger = "0.10"
rav1e = "0.7"
pollster = "0.3"
imgui = { path = "./imgui-rs/imgui" }
imgui-winit-support = { path = "./imgui-rs/imgui-winit-support" }
imgui-wgpu = { path = "./imgui-wgpu" }

[target.'cfg(not(target_family = "wasm"))'.dependencies.winit]
version = "0.29.3"
features = ["rwh_05", "wayland", "x11"]

[target.'cfg(target_family = "wasm")'.dependencies]
console_log = { version="0.2", features=["color"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlCanvasElement"] }
