[workspace]
members = ["triangle"]

[package]
name = "aftgraphs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
futures-intrusive = "0.5.0"
wgpu = { version="0.18", features=["webgl", "spirv"] }
winit = { version="0.29", features=["rwh_05"] }
current_platform = "0.2"
async-mutex = "1.4.0"
log = "0.4.20"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
clap = "4.4"
env_logger = "0.10.1"
rav1e = "0.7"
pollster = "0.3.0"

[target.'cfg(target_family = "wasm")'.dependencies]
console_log = { version="0.2", features=["color"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Window", "Document", "Element", "HtmlCanvasElement"] }

[profile.release]
lto = true
